name: CI/CD FastTech Foods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_PREFIX: fasttechfood

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and test IdentityApi
        run: |
          cd src/IdentityApi
          dotnet restore
          dotnet build --configuration Release
          dotnet test --no-build --verbosity normal

      - name: Build and test MenuApi
        run: |
          cd src/MenuApi
          dotnet restore
          dotnet build --configuration Release
          dotnet test --no-build --verbosity normal

      - name: Build and test OrderApi
        run: |
          cd src/OrderApi
          dotnet restore
          dotnet build --configuration Release
          dotnet test --no-build --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push IdentityApi image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/IdentityApi/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-identityapi:latest

      - name: Build