version: '3.8'

services:
  postgres_identity:
    image: postgres:15
    container_name: postgres_identity
    environment:
      POSTGRES_USER: fasttech
      POSTGRES_PASSWORD: fasttech123
      POSTGRES_DB: fasttech_identity
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - fasttech-network

networks:
  fasttech-network:
    driver: bridge
