version: '3.8'

services:
  postgres_identity:
    image: postgres:latest
    restart: always
    container_name: postgres_identity
    environment:
      POSTGRES_USER: fasttech
      POSTGRES_PASSWORD: fasttech123
      POSTGRES_DB: fasttech_identity
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - fasttech-network

  postgres_menu:
    image: postgres:latest
    container_name: postgres_menu
    environment:
      POSTGRES_USER: fasttech
      POSTGRES_PASSWORD: fasttech123
      POSTGRES_DB: fasttech_menu
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - fasttech-network

  postgres_order:
    image: postgres:latest
    container_name: postgres_order
    environment:
      POSTGRES_USER: fasttech
      POSTGRES_PASSWORD: fasttech123
      POSTGRES_DB: fasttech_order
    ports:
      - "5434:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - fasttech-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fasttech-network

  identityapi:
    build:
      context: .
      dockerfile: src/IdentityApi/Dockerfile
    container_name: fasttech_identityapi
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_identity;Port=5432;Database=fasttech_identity;Username=fasttech;Password=fasttech123
    depends_on:
      - postgres_identity
    networks:
      - fasttech-network

  menuapi:
    build:
      context: .
      dockerfile: src/MenuApi/Dockerfile
    container_name: fasttech_menuapi
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_menu;Port=5432;Database=fasttech_menu;Username=fasttech;Password=fasttech123
    depends_on:
      - postgres_menu
    networks:
      - fasttech-network

  orderapi:
    build:
      context: .
      dockerfile: src/OrderApi/Dockerfile
    container_name: fasttech_orderapi
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - postgres_order
    networks:
      - fasttech-network
  zabbix-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - ./docker/zabbix/db:/var/lib/postgresql/data
    networks:
      - fasttech-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_STARTPOLLERS: 5
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    volumes:
      - ./docker/zabbix/server:/var/lib/zabbix
    networks:
      - fasttech-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - zabbix-server
    ports:
      - "8085:8080"
    volumes:
      - ./docker/zabbix/web:/etc/ssl/nginx
    networks:
      - fasttech-network

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - fasttech-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    depends_on:
      - zabbix-server
    networks:
      - fasttech-network
networks:
  fasttech-network:
    driver: bridge