apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
    component: monitoring
    type: datasources
    version: v1.0.0
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Zabbix
        type: alexanderzobnin-zabbix-datasource
        access: proxy
        url: http://zabbix-web:80/api_jsonrpc.php
        isDefault: false
        jsonData:
          username: Admin
          trends: true
          trendsFrom: "7d"
          trendsRange: "4d"
          cacheTTL: "1h"
          timeout: "30s"
          keepCookies: []
        secureJsonData:
          password: zabbix
        editable: true
        
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
