apiVersion: v1
kind: ConfigMap
metadata:
  name: identityapi-config
data:
  ConnectionStrings__DefaultConnection: "Host=postgres-identity;Port=5432;Database=fasttech_identity;Username=fasttech;Password=fasttech123"