apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuapi
  template:
    metadata:
      labels:
        app: menuapi
    spec:
      containers:
      - name: menuapi
        image: fasttechfood-menuapi:latest
        imagePullPolicy: Never  # Usar imagem local do Minikube
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: menuapi-config
              key: ConnectionStrings__DefaultConnection
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
