apiVersion: v1
kind: Service
metadata:
  name: menuapi-service
  labels:
    app: menuapi
    component: backend
    service: menu
    type: service
    version: v1.0.0
spec:
  selector:
    app: menuapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort