apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
  labels:
    app: orderapi
    component: backend
    service: order
    type: service
    version: v1.0.0
spec:
  selector:
    app: orderapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort