apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-menu
  template:
    metadata:
      labels:
        app: postgres-menu
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: fasttech_menu
        - name: POSTGRES_USER
          value: fasttech
        - name: POSTGRES_PASSWORD
          value: fasttech123
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-menu-pvc-hostpath