apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    component: messaging
    version: v3.12.8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        component: messaging
        version: v3.12.8
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12.8-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: fasttech
        - name: RABBITMQ_DEFAULT_PASS
          value: fasttech123