apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-web-pv-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/zabbix-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-web-pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
