apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app: zabbix-web
    component: monitoring
    service: zabbix-web
    version: v7.4.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
        component: monitoring
        service: zabbix-web
        version: v7.4.0
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:alpine-7.4.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER_HOST
          value: postgres-zabbix
        - name: POSTGRES_USER
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: zabbix
        - name: POSTGRES_DB
          value: zabbix
        - name: ZBX_SERVER_HOST
          value: zabbix-server
        volumeMounts:
        - name: zabbix-web-data
          mountPath: /etc/zabbix/web
        - name: zabbix-web-config
          mountPath: /usr/share/zabbix/conf
      volumes:
      - name: zabbix-web-data
        persistentVolumeClaim:
          claimName: zabbix-web-pvc-hostpath
      - name: zabbix-web-config
        configMap:
          name: zabbix-web-config