apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
    component: monitoring
    service: zabbix-server
    version: v7.4.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
        component: monitoring
        service: zabbix-server
        version: v7.4.0
    spec:
      initContainers:
      - name: zabbix-db-init
        image: zabbix/zabbix-server-pgsql:alpine-7.4.0
        command: ['sh', '-c']
        args:
        - |
          echo "Aguardando PostgreSQL..."
          until pg_isready -h postgres-zabbix -p 5432; do
            echo "PostgreSQL não está pronto, aguardando..."
            sleep 2
          done
          echo "PostgreSQL está pronto!"
        env:
        - name: DB_SERVER_HOST
          value: postgres-zabbix
        - name: POSTGRES_USER
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: zabbix
        - name: POSTGRES_DB
          value: zabbix
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:alpine-7.4.0
        ports:
        - containerPort: 10051
        env:
        - name: DB_SERVER_HOST
          value: postgres-zabbix
        - name: POSTGRES_USER
          value: zabbix
        - name: POSTGRES_PASSWORD
          value: zabbix
        - name: POSTGRES_DB
          value: zabbix
        volumeMounts:
        - name: zabbix-data
          mountPath: /var/lib/zabbix
      volumes:
      - name: zabbix-data
        persistentVolumeClaim:
          claimName: zabbix-pvc-hostpath