apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-server-config
  labels:
    app: zabbix-server
    component: monitoring
    service: zabbix-server
    type: config
    version: v7.4.0
data:
  zabbix_server.conf: |
    LogFile=/var/log/zabbix/zabbix_server.log
    LogFileSize=10
    PidFile=/var/run/zabbix/zabbix_server.pid
    SocketDir=/var/run/zabbix
    DBHost=postgres-identity
    DBName=fasttech_identity
    DBUser=fasttech
    DBPassword=fasttech123
    DBSocket=
    DBPort=5432
    StartPollers=5
    StartIPMIPollers=0
    StartPollersUnreachable=1
    StartTrappers=5
    StartPingers=1
    StartDiscoverers=1
    StartHTTPPollers=1
    StartTimers=1
    StartEscalators=1
    JavaGateway=127.0.0.1
    JavaGatewayPort=10052
    StartJavaPollers=0
    StartVMwareCollectors=0
    VMwareFrequency=60
    VMwarePerfFrequency=60
    VMwareCacheSize=8M
    VMwareTimeout=10
    SNMPTrapperFile=/var/log/snmptrap/snmptrap.log
    StartSNMPTrapper=0
    ListenIP=0.0.0.0
    ListenPort=10051
    HousekeepingFrequency=1
    MaxHousekeeperDelete=5000
    CacheSize=8M
    CacheUpdateFrequency=60
    StartDBSyncers=4
    HistoryCacheSize=16M
    HistoryIndexCacheSize=4M
    TrendCacheSize=4M
    ValueCacheSize=8M
    Timeout=4
    TrapperTimeout=300
    UnreachablePeriod=45
    UnavailableDelay=60
    UnreachableDelay=15
    AlertScriptsPath=/usr/lib/zabbix/alertscripts
    ExternalScripts=/usr/lib/zabbix/externalscripts
    FpingLocation=/usr/bin/fping
    Fping6Location=/usr/bin/fping6
    SSHKeyLocation=
    LogSlowQueries=3000
    TmpDir=/tmp
    StartProxyPollers=1
    ProxyConfigFrequency=3600
    ProxyDataFrequency=1
    AllowRoot=0
    User=zabbix
    Include=/usr/local/share/zabbix/include/
    SSLCertLocation=/usr/local/share/zabbix/ssl/certs/
    SSLKeyLocation=/usr/local/share/zabbix/ssl/keys/
    SSLCALocation=/usr/local/share/zabbix/ssl/ssl_ca/
    LoadModulePath=/usr/lib/zabbix/modules
    TLSCAFile=
    TLSCRLFile=
    TLSCertFile=
    TLSKeyFile=
