apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-pv-hostpath
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/zabbix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
