apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-web-config
data:
  maintenance.inc.php: |
    <?php
    return false;
  zabbix.conf.php: |
    <?php
    global $DB, $HISTORY;
    
    $DB['TYPE']     = 'POSTGRESQL';
    $DB['SERVER']   = 'postgres-zabbix';
    $DB['PORT']     = '5432';
    $DB['DATABASE'] = 'zabbix';
    $DB['USER']     = 'zabbix';
    $DB['PASSWORD'] = 'zabbix';
    
    $ZBX_SERVER      = 'zabbix-server';
    $ZBX_SERVER_PORT = '10051';
    $ZBX_SERVER_NAME = 'Fast Food Monitoring';
    
    $IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
